package me.dreadiscool.wrapper;

public class BlockType {

	public static final byte AIR = (byte)0;
    public static final byte STONE = (byte)1;
    public static final byte GRASS = (byte)2;
    public static final byte DIRT = (byte)3;
    public static final byte COBBLESTONE = (byte)4;
    public static final byte WOOD = (byte)5;
    public static final byte SHRUB = (byte)6;
    public static final byte BEDROCK = (byte)7;
    public static final byte WATER = (byte)8;
    public static final byte STILLWATER = (byte)9;
    public static final byte LAVA = (byte)10;
    public static final byte STILLLAVA = (byte)11;
    public static final byte SAND = (byte)12;
    public static final byte GRAVEL = (byte)13;
    public static final byte GOLD_ORE = (byte)14;
    public static final byte IRON_ORE = (byte)15;
    public static final byte COAL_ORE = (byte)16;
    public static final byte LOG = (byte)17;
    public static final byte LEAVES = (byte)18;
    public static final byte SPONGE = (byte)19;
    public static final byte GLASS = (byte)20;
    public static final byte WOOL_RED = (byte)21;
    public static final byte WOOL_ORANGE = (byte)22;
    public static final byte WOOL_YELLOW = (byte)23;
    public static final byte WOOL_LIGHT_GREEN = (byte)24;
    public static final byte WOOL_GREEN = (byte)25;
    public static final byte WOOL_AQUA = (byte)26;
    public static final byte WOOL_CYAN = (byte)27;
    public static final byte WOOL_LIGHT_BLUE = (byte)28;
    public static final byte WOOL_BLUE = (byte)29;
    public static final byte WOOL_PURPLE = (byte)30;
    public static final byte WOOL_LIGHT_PURPLE = (byte)31;
    public static final byte WOOL_PINK = (byte)32;
    public static final byte WOOL_DARK_PINK = (byte)33;
    public static final byte WOOL_DARK_GRAY = (byte)34;
    public static final byte WOOL_LIGHT_GRAY = (byte)35;
    public static final byte WOOL_WHITE = (byte)36;
    public static final byte FLOWER_YELLOW = (byte)37;
    public static final byte FLOWER_RED = (byte)38;
    public static final byte MUSHROOM_REGULAR = (byte)39;
    public static final byte MUSHROOM_RED = (byte)40;
    public static final byte GOLD_BLOCK = (byte)41;
    public static final byte IRON_BLOCK = (byte)42;
    public static final byte DOUBLE_STEP = (byte)43;
    public static final byte STONE_SLAB = (byte)44;
    public static final byte BRICKS = (byte)45;
    public static final byte TNT = (byte)46;
    public static final byte BOOKSHELF = (byte)47;
    public static final byte MOSSY_COBBLE = (byte)48;
    public static final byte OBSIDIAN = (byte)49;
    public static final byte Zero = (byte)0xff;
}
